services:

  db:
    build: ./requirements/mariadb/.
    container_name: inception_db
    ports: 
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    env_file: .env
    restart: always

  wordpress:
    build: ./requirements/wordpress/.
    depends_on:
      - db
    container_name: inception_wp
    expose:
      - '9000'
    volumes:
      - ./requirements/wordpress_data/wordpress_data:/var/www/html
#      - ./requirements/wordpress_data/wordpress_data:/var/www/html/wordpress_data
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    networks:
      - app-network
    env_file: .env
    restart: always

  nginx:
    build: ./requirements/nginx/.
    depends_on:
      - wordpress
    container_name: inception_nginx
    ports:
      - '8443:443'
      - '8080:80'
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./requirements/wordpress_data/wordpress_data:/var/www/html
    networks:
      - app-network
    env_file: .env
    restart: always

networks:
  app-network:

volumes:
  db_data: